name: SimpleSpawn
version: '1.0'
main: de.donythepony.simplespawn.Main

commands:
  setspawn:
    description: sets spawn.
    permission: simplespawn.create
    usage: /<command>
  spawn:
    description: spawns at spawnlocation.
    usage: /<command>